// Generated by @carbos/varlink from io.example.Fixture.varlink. Do not edit.

import { defineInterface, type Empty, type Handler, type Interface, VarlinkError } from "@carbos/varlink";

export const description = `# Covers every construct the generator handles. Backticks \` and \${x} survive.
interface io.example.Fixture

type Mode (fast, slow)

type Thing (
  # Documented.
  flag: bool,
  count: int,
  ratio: float,
  label: ?string,
  extra: object,
  tags: []?string,
  byName: [string]Mode,
  inline: (x: int),
  mode: (on, off)
)

method Get(id: string) -> (thing: Thing)

method Ping() -> ()

error Missing (id: string)
error Busy ()
`;

export type Mode = "fast" | "slow";

export interface Thing {
  /** Documented. */
  readonly flag: boolean;
  readonly count: number;
  readonly ratio: number;
  readonly label?: string | null;
  readonly extra: Readonly<Record<string, unknown>>;
  readonly tags: readonly (string | null)[];
  readonly byName: Readonly<Record<string, Mode>>;
  readonly inline: { readonly x: number };
  readonly mode: "on" | "off";
}

export type Methods = {
  readonly Get: Handler<
    { readonly id: string },
    { readonly thing: Thing }
  >;
  readonly Ping: Handler<
    Empty,
    Empty
  >;
};

export const errors = {
  Missing: (parameters: { readonly id: string }): VarlinkError => new VarlinkError("io.example.Fixture.Missing", parameters),
  Busy: (): VarlinkError => new VarlinkError("io.example.Fixture.Busy"),
};

export const implement = (handlers: Methods): Interface => defineInterface(description, handlers);
