// Generated by @carbos/varlink from io.siku2.VoiceCall.varlink. Do not edit.

import { defineInterface, type Empty, type Handler, type Interface, VarlinkError } from "@carbos/varlink";

export const description = `# Voice call state of a chat client, for desktop widgets.
interface io.siku2.VoiceCall

# One rendition of an image, in pixels.
type Image (
  url: string,
  width: int,
  height: int
)

type Participant (
  # Opaque and stable. A string, since chat IDs can exceed 2^53.
  id: string,
  name: string,
  # Smallest first. Empty if there is no avatar.
  avatar: []Image,
  speaking: bool,
  # Muted by themselves.
  selfMuted: bool,
  selfDeafened: bool,
  # Muted by the server, for everyone.
  serverMuted: bool,
  serverDeafened: bool,
  # Muted by the local user, for themselves only.
  locallyMuted: bool,
  # The local user.
  self: bool
)

type Call (
  # Changes when the user switches to another channel.
  id: string,
  # The channel name, or the other person's name in a direct call.
  name: string,
  # Null for direct and group calls.
  server: ?string,
  # In the order the client shows them.
  participants: []Participant
)

type State (
  # The local user's own toggles. They persist across calls.
  muted: bool,
  deafened: bool,
  call: ?Call
)

# Replies with the current state. With "more", replies again on every change.
method Watch() -> (state: State)

method SetMute(muted: bool) -> ()
method SetDeafen(deafened: bool) -> ()

# Leaves the current call. With an id, only if that call is still the current one.
method LeaveCall(id: ?string) -> ()

# There is no call, or not the given one.
error NotInCall ()
`;

/** One rendition of an image, in pixels. */
export interface Image {
  readonly url: string;
  readonly width: number;
  readonly height: number;
}

export interface Participant {
  /** Opaque and stable. A string, since chat IDs can exceed 2^53. */
  readonly id: string;
  readonly name: string;
  /** Smallest first. Empty if there is no avatar. */
  readonly avatar: readonly Image[];
  readonly speaking: boolean;
  /** Muted by themselves. */
  readonly selfMuted: boolean;
  readonly selfDeafened: boolean;
  /** Muted by the server, for everyone. */
  readonly serverMuted: boolean;
  readonly serverDeafened: boolean;
  /** Muted by the local user, for themselves only. */
  readonly locallyMuted: boolean;
  /** The local user. */
  readonly self: boolean;
}

export interface Call {
  /** Changes when the user switches to another channel. */
  readonly id: string;
  /** The channel name, or the other person's name in a direct call. */
  readonly name: string;
  /** Null for direct and group calls. */
  readonly server?: string | null;
  /** In the order the client shows them. */
  readonly participants: readonly Participant[];
}

export interface State {
  /** The local user's own toggles. They persist across calls. */
  readonly muted: boolean;
  readonly deafened: boolean;
  readonly call?: Call | null;
}

export type Methods = {
  /** Replies with the current state. With "more", replies again on every change. */
  readonly Watch: Handler<
    Empty,
    { readonly state: State }
  >;
  readonly SetMute: Handler<
    { readonly muted: boolean },
    Empty
  >;
  readonly SetDeafen: Handler<
    { readonly deafened: boolean },
    Empty
  >;
  /** Leaves the current call. With an id, only if that call is still the current one. */
  readonly LeaveCall: Handler<
    { readonly id?: string | null },
    Empty
  >;
};

export const errors = {
  /** There is no call, or not the given one. */
  NotInCall: (): VarlinkError => new VarlinkError("io.siku2.VoiceCall.NotInCall"),
};

export const implement = (handlers: Methods): Interface => defineInterface(description, handlers);
