import { parse, type StructType, type Type } from "./idl.ts";

export interface GenerateOptions {
  /** Named in the header comment. */
  readonly file: string;
  /** Where the generated module imports the runtime from. */
  readonly runtime: string;
}

// Every name the generated module declares or imports.
const reserved = new Set([
  "defineInterface",
  "description",
  "Empty",
  "errors",
  "Handler",
  "implement",
  "Interface",
  "Methods",
  "VarlinkError",
]);

/** Turns an interface description into a TypeScript module. */
export function generate(source: string, options: GenerateOptions): string {
  const schema = parse(source);
  const lines = [
    `// Generated by @carbos/varlink from ${options.file}. Do not edit.`,
    "",
    `import { defineInterface, type Empty, type Handler, type Interface, VarlinkError } from "${options.runtime}";`,
    "",
    `export const description = \`${source.replace(/[\\`]|\$\{/g, "\\$&")}\`;`,
  ];

  for (const { name, type, doc } of schema.types.values()) {
    if (reserved.has(name)) {
      throw new Error(
        `${options.file}: the type "${name}" clashes with a generated export`,
      );
    }
    lines.push("", ...docComment(doc, ""));
    if (type.kind === "struct" && type.fields.length > 0) {
      lines.push(`export interface ${name} ${renderStruct(type, "")}`);
    } else {
      lines.push(`export type ${name} = ${render(type, "")};`);
    }
  }

  lines.push("", "export type Methods = {");
  for (const { name, input, output, doc } of schema.methods.values()) {
    lines.push(
      ...docComment(doc, "  "),
      `  readonly ${name}: Handler<`,
      `    ${renderStruct(input, "    ")},`,
      `    ${renderStruct(output, "    ")}`,
      "  >;",
    );
  }
  lines.push("};", "", "export const errors = {");
  for (const { name, parameters, doc } of schema.errors.values()) {
    const qualified = JSON.stringify(`${schema.name}.${name}`);
    lines.push(
      ...docComment(doc, "  "),
      parameters.fields.length === 0
        ? `  ${name}: (): VarlinkError => new VarlinkError(${qualified}),`
        : `  ${name}: (parameters: ${renderStruct(parameters, "  ")}): VarlinkError => new VarlinkError(${qualified}, parameters),`,
    );
  }
  lines.push(
    "};",
    "",
    "export const implement = (handlers: Methods): Interface => defineInterface(description, handlers);",
    "",
  );
  return lines.join("\n");
}

function render(type: Type, indent: string): string {
  switch (type.kind) {
    case "bool":
      return "boolean";
    case "int":
    case "float":
      return "number";
    case "string":
      return "string";
    case "object":
      return "Readonly<Record<string, unknown>>";
    case "nullable":
      return `${render(type.element, indent)} | null`;
    case "array": {
      const element = render(type.element, indent);
      const union =
        type.element.kind === "nullable" || type.element.kind === "enum";
      return `readonly ${union ? `(${element})` : element}[]`;
    }
    case "map":
      return `Readonly<Record<string, ${render(type.element, indent)}>>`;
    case "enum":
      return type.values.map((value) => JSON.stringify(value)).join(" | ");
    case "struct":
      return renderStruct(type, indent);
    case "named":
      return type.name;
  }
}

function renderStruct(struct: StructType, indent: string): string {
  if (struct.fields.length === 0) return "Empty";

  const short = struct.fields.map(
    ({ name, type }) =>
      `readonly ${name}${type.kind === "nullable" ? "?" : ""}: ${render(type, "")}`,
  );
  const line = `{ ${short.join("; ")} }`;
  if (
    struct.fields.every(({ doc }) => doc === "") &&
    !line.includes("\n") &&
    line.length <= 60
  ) {
    return line;
  }

  const inner = `${indent}  `;
  const fields = struct.fields.flatMap(({ name, type, doc }) => [
    ...docComment(doc, inner),
    `${inner}readonly ${name}${type.kind === "nullable" ? "?" : ""}: ${render(type, inner)};`,
  ]);
  return ["{", ...fields, `${indent}}`].join("\n");
}

function docComment(doc: string, indent: string): string[] {
  if (doc === "") return [];
  const lines = doc.replaceAll("*/", "*\\/").split("\n");
  if (lines.length === 1) return [`${indent}/** ${lines[0]} */`];
  return [
    `${indent}/**`,
    ...lines.map((line) => `${indent} * ${line}`.trimEnd()),
    `${indent} */`,
  ];
}
